echo "Welcome to debloat"
echo ""
echo " Debloat By Lusara"
sleep 3
echo " Telegram : @Lusaraemd "
sleep 3
pm uninstall --user 0 com.google.android.syncadap
pm uninstall --user 0  com.google.android.tts
pm uninstall --user 0  com.samsung.android.dynamic
pm uninstall --user 0  com.samsung.android.calenda
pm uninstall --user 0 com.skms.android.agent
pm uninstall --user 0 com.sec.factorypm
pm uninstall --user 0 com.sec.android.wallpapercropper2pm 
pm uninstall --user 0 com.sec.android.app.factorykeystringpm 
pm uninstall --user 0 com.sec.android.app.wlantestpm 
pm uninstall --user 0 com.sec.svepm 
pm uninstall --user 0 com.sec.android.providers.securitypm 
pm uninstall --user 0 com.samsung.android.securitylogagentpm 
pm uninstall --user 0 com.samsung.SMTpm 
pm uninstall --user 0 com.samsung.android.aircommandmanagerpm 
pm uninstall --user 0 com.samsung.android.camerasdkservicepm 
pm uninstall --user 0 com.samsung.android.smartfittingpm 
pm uninstall --user 0 com.sec.android.app.SecSetupWizardpm 
pm uninstall --user 0 com.sec.android.app.hwmoduletestpm 
pm uninstall --user 0 com.sec.bcservicepm 
pm uninstall --user 0 com.sec.modem.settingspm 
pm uninstall --user 0 com.sec.android.preloadinstallerpm 
pm uninstall --user 0 com.sec.android.uibcvirtualsoftkeypm 
pm uninstall --user 0 com.sec.imsservicepm 
pm uninstall --user 0 com.samsung.android.da.daagentpm 
pm uninstall --user 0 com.samsung.advp.imssettingspm 
pm uninstall --user 0 com.sec.imsloggerpm 
pm uninstall --user 0 com.sec.android.diagmonagentpm 
pm uninstall --user 0 com.samsung.android.dqagentpm 
pm uninstall --user 0 com.samsung.android.stickercenterpm 
pm uninstall --user 0 com.samsung.android.fmmpm 
pm uninstall --user 0 com.sec.app.RilErrorNotifierpm 
pm uninstall --user 0 com.samsung.android.svcagentpm 
pm uninstall --user 0 com.samsung.android.shortcutbackupservicepm 
pm uninstall --user 0 com.samsung.memorysaverpm 
pm uninstall --user 0 com.android.wallpaperbackuppm 
pm uninstall --user 0 com.samsung.android.app.omcagentpm 
pm uninstall --user 0 com.sec.android.app.personalizationpm 
pm uninstall --user 0 com.samsung.sait.sohservicepm 
pm uninstall --user 0 com.samsung.aasaservicepm 
pm uninstall --user 0 com.samsung.logwriterpm 
pm uninstall --user 0 com.samsung.android.bio.face.servicepm 
pm uninstall --user 0 com.android.mms.servicepm 
pm uninstall --user 0 com.sec.imspm 
pm uninstall --user 0 com.sec.android.CarrierCodeChangerpm 
pm uninstall --user 0 com.sec.android.RilServiceModeApppm 
pm uninstall --user 0 com.samsung.cranepm 
pm uninstall --user 0 com.sec.phonepm 
pm uninstall --user 0 com.sec.android.app.safetyassurancepm 
pm uninstall --user 0 com.samsung.cmhpm 
pm uninstall --user 0 com.samsung.mlppm 
pm uninstall --user 0 com.samsung.storyservicepm 
pm uninstall --user 0 com.samsung.ipservicepm 
pm uninstall --user 0 com.samsung.android.allshare.service.filesharepm 
pm uninstall --user 0 com.samsung.android.beaconmanagerpm 
pm uninstall --user 0 com.samsung.android.allshare.service.mediasharepm 
pm uninstall --user 0 com.samsung.android.scloudpm 
pm uninstall --user 0 com.samsung.android.rubin.apppm 
pm uninstall --user 0 com.samsung.android.sm.devicesecuritypm 
pm uninstall --user 0 com.sec.location.nsflp2pm 
pm uninstall --user 0 com.samsung.android.samsungpositioningpm 
pm uninstall --user 0 com.samsung.android.ipsgeofencepm 
pm uninstall --user 0 com.samsung.android.networkdiagnosticpm 
pm uninstall --user 0 com.sec.android.easyonehandpm 
pm uninstall --user 0 com.samsung.android.aremojipm 
pm uninstall --user 0 com.android.calllogbackuppm 
pm uninstall --user 0 com.sec.android.mimage.avatarstickerspm 
pm uninstall --user 0 com.google.android.configupdaterpm 
pm uninstall --user 0 com.samsung.android.app.siofviewerpm 
pm uninstall --user 0 com.samsung.android.app.dofviewerpm 
pm uninstall --user 0 com.samsung.android.easysetuppm 
pm uninstall --user 0 com.samsung.android.emojiupdaterpm 
pm uninstall --user 0 com.facebook.servicespm 
pm uninstall --user 0 com.samsung.android.app.galaxyfinderpm 
pm uninstall --user 0 com.sec.android.widgetapp.samsungappspm 
pm uninstall --user 0 com.samsung.android.game.gametoolspm 
pm uninstall --user 0 com.google.android.backuptransportpm 
pm uninstall --user 0 com.samsung.android.game.gamehomepm 
pm uninstall --user 0 com.google.android.feedbackpm 
pm uninstall --user 0 com.sec.android.app.samsungappspm 
pm uninstall --user 0 com.google.android.partnersetuppm 
pm uninstall --user 0 com.sec.android.app.fmpm 
pm uninstall --user 0 com.samsung.klmsagentpm 
pm uninstall --user 0 com.samsung.android.keyguardwallpaperupdatorpm 
pm uninstall --user 0 com.samsung.android.mateagentpm 
pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapppm 
pm uninstall --user 0 com.wsomacppm 
pm uninstall --user 0 com.microsoft.skydrivepm 
pm uninstall --user 0 com.sec.spp.pushpm 
pm uninstall --user 0 com.osp.app.signinpm 
pm uninstall --user 0 com.sec.android.app.billingpm 
pm uninstall --user 0 com.sec.android.app.magnifierpm 
pm uninstall --user 0 com.samsung.android.mobileservicepm 
pm uninstall --user 0 com.samsung.android.app.socialpm 
pm uninstall --user 0 com.android.sharedstoragebackuppm 
pm uninstall --user 0 com.google.android.setupwizardpm 
pm uninstall --user 0 com.samsung.android.smartcallproviderpm 
pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preloadpm 
pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearexpression.preloadpm 
pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearframe.preloadpm 
pm uninstall --user 0 com.samsung.android.themestorepm 
pm uninstall --user 0 com.google.android.ext.sharedpm 
pm uninstall --user 0 com.sec.factory.cameralyzerpm 
pm uninstall --user 0 com.sec.android.app.ve.vebgmpm 
pm uninstall --user 0 com.samsung.android.game.gospm 
pm uninstall --user 0 com.monotype.android.font.foundationpm 
pm uninstall --user 0 com.sec.android.splitsoundpm 
pm uninstall --user 0 com.google.android.apps.mapspm 
pm uninstall --user 0 com.google.android.printservice.recommendationpm 
pm uninstall --user 0 com.google.android.syncadapters.contactspm 
pm uninstall --user 0 com.sec.android.widgetapp.webmanualpm 
pm uninstall --user 0 com.google.android.marvin.talkbackpm 
pm uninstall --user 0 com.android.bipspm 
pm uninstall --user 0 com.sec.android.app.chromecustomizationspm 
pm uninstall --user 0 com.monotype.android.font.samsungonepm 
pm uninstall --user 0 com.enhance.gameservicepm 
pm uninstall --user 0 com.samsung.android.app.watchmanagerstubpm 
pm uninstall --user 0 com.samsung.safetyinformationpm 
pm uninstall --user 0 android.autoinstalls.config.samsungpm 
pm uninstall --user 0 com.samsung.android.locationpm 
pm uninstall --user 0 com.sec.unifiedwfcpm 
pm uninstall --user 0 com.samsung.android.sm.policypm 
pm uninstall --user 0 com.android.pacprocessorpm 
pm uninstall --user 0 com.netflix.partner.activationpm 
pm uninstall --user 0 com.hiya.starpm 
pm uninstall --user 0 com.sec.android.app.DataCreatepm 
pm uninstall --user 0 com.samsung.android.smartmirroringpm 
pm uninstall --user 0 com.sec.android.daemonapppm 
pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdmspm 
pm uninstall --user 0 com.samsung.android.lwepm 
pm uninstall --user 0 com.netflix.mediaclientpm 
pm uninstall --user 0 com.sec.android.easyMover.Agentpm 
pm uninstall --user 0 com.aura.oobe.samsungpm 
pm uninstall --user 0 com.opera.max.preinstallpm 
pm uninstall --user 0 com.samsung.android.mfipm 
pm uninstall --user 0 com.mobigraph.xpresso.sliceapppm 
pm uninstall --user 0 com.mygalaxypm 
pm uninstall --user 0 com.samsung.android.game.gospm 
pm uninstall --user 0 com.samsungvietnam.quatanggalaxypm 
pm uninstall --user 0 com.samsung.android.app.watchmanagerpm 
pm uninstall --user 0 com.samsung.android.email.providerpm 
pm uninstall --user 0 com.sec.android.app.voicenotepm 
pm uninstall --user 0 com.google.android.musicpm 
pm uninstall --user 0 com.google.android.videospm 
pm uninstall --user 0 com.linkedin.androidpm 
pm uninstall --user 0 com.google.android.apps.tachyonpm 
pm uninstall --user 0 com.samsung.android.app.panel.naver.vpm 
pm uninstall --user 0 com.sec.android.app.shealthpm 
pm uninstall --user 0 com.samsung.android.vocpm 
pm uninstall --user 0 com.samsung.android.app.notespm 
pm uninstall --user 0 com.samsung.android.spaypm 
pm uninstall --user 0 com.sec.android.easymoverpm 
pm uninstall --user 0 com.rsupport.rs.activity.rsupport.aas2pm 
pm uninstall --user 0 com.sec.android.service.healthpm 
pm uninstall --user 0 com.android.printspoolerpm 
pm uninstall --user 0 com.sec.android.mimage.gear360editorpm 
pm uninstall --user 0 com.samsung.android.oneconnectpm 
pm uninstall --user 0 com.samsung.android.bixby.agentpm 
pm uninstall --user 0 com.microsoft.office.excelpm 
pm uninstall --user 0 com.microsoft.office.powerpointpm 
pm uninstall --user 0 com.android.traceurpm 
pm uninstall --user 0 com.google.android.apps.docs.editors.sheetspm 
pm uninstall --user 0 com.google.mainline.adservicespm 
pm uninstall --user 0 com.google.android.adservices.apipm 
pm uninstall --user 0 com.android.bookmarkproviderpm 
pm uninstall --user 0 com.android.dreams.basicpm 
pm uninstall --user 0 com.android.dreams.phototablepm 
pm uninstall --user 0 com.android.eggpm 
pm uninstall --user 0 com.android.hotwordenrollment.okgooglepm 
pm uninstall --user 0 com.android.hotwordenrollment.xgooglepm 
pm uninstall --user 0 com.android.providers.partnerbookmarkspm 
pm uninstall --user 0 com.sec.android.app.samsungappspm 
pm uninstall --user 0 com.samsung.android.dynamiclockpm 
pm uninstall --user 0 com.samsung.android.tvpluspm 
pm uninstall --user 0 com.samsung.android.app.watchmanagerstubpm 
pm uninstall --user 0 com.samsung.android.app.watchmanagerpm 
pm uninstall --user 0 com.samsung.android.waterpluginpm 
pm uninstall --user 0 com.samsung.android.accessibility.talkbackpm 
pm uninstall --user 0 com.samsung.android.app.settings.bixbypm 
pm uninstall --user 0 com.samsung.android.bixby.wakeuppm 
pm uninstall --user 0 com.samsung.android.bixby.agentpm 
pm uninstall --user 0 com.samsung.android.bixbyvision.frameworkpm 
pm uninstall --user 0 com.sec.android.app.shealthpm 
pm uninstall --user 0 com.samsung.android.arzonepm 
pm uninstall --user 0 com.google.android.apps.docspm 
pm uninstall --user 0 com.google.android.apps.tachyonpm 
pm uninstall --user 0 com.google.android.feedbackpm 
pm uninstall --user 0 com.google.android.googlequicksearchboxpm 
pm uninstall --user 0 com.google.android.marvin.talkbackpm 
pm uninstall --user 0 com.google.android.printservice.recommendationpm 
pm uninstall --user 0 com.google.android.syncadapters.calendarpm 
pm uninstall --user 0 com.google.android.ttspm 
pm uninstall --user 0 com.google.android.apps.youtube.musicpm 
pm uninstall --user 0 com.google.ar.corepm 
pm uninstall --user 0 com.sec.android.mimage.avatarstickerspm 
pm uninstall --user 0 com.samsung.android.aremojieditorpm 
pm uninstall --user 0 com.android.bipspm 
pm uninstall --user 0 com.samsung.android.game.gametoolspm 
pm uninstall --user 0 com.samsung.android.game.gospm 
pm uninstall --user 0 com.samsung.android.kidsinstallerpm 
pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preloadpm 
pm uninstall --user 0 com.sec.android.app.sbrowserpm 
pm uninstall --user 0 com.sec.android.easyMover.Agentpm 
pm uninstall --user 0 com.samsung.android.calendarpm 
pm uninstall --user 0 com.sec.android.dexsystemuipm 
pm uninstall --user 0 com.sec.android.app.desktoplauncherpm 
pm uninstall --user 0 com.synchronoss.dcs.att.r2gpm 
pm uninstall --user 0 com.wavemarket.waplauncherpm 
pm uninstall --user 0 com.pandora.androidpm 
pm uninstall --user 0 com.sec.penuppm 
pm uninstall --user 0 com.wb.goog.got.conquestpm 
pm uninstall --user 0 com.foxnextgames.m3pm 
pm uninstall --user 0 com.microsoft.skydrivepm 
pm uninstall --user 0 com.claromusicapm 
pm uninstall --user 0 com.clarovideopm 
pm uninstall --user 0 com.clarocloudpm 
pm uninstall --user 0 com.claroshoppm 
pm uninstall --user 0 com.claropaypm 
pm uninstall --user 0 com.claro.tvpm 
pm uninstall --user 0 com.claro.empresaspm 
pm uninstall --user 0 com.claro.assistantpm 
pm uninstall --user 0 com.claro.photoeditorpm 
pm uninstall --user 0 com.claro.storepm 
echo " Thanks for Using debloat"
sleep 2
echo ""
echo "I will update new packages to optimize the experience."
echo " Goodbye"
sleep 2