echo " Restore Package"
echo ""
echo " Telegram : @Lusaraemd"
sleep 2 
cmd package install-existing com.google.android.syncadap
cmd package install-existing  com.google.android.tts
cmd package install-existing  com.samsung.android.dynamic
cmd package install-existing  com.samsung.android.calenda
cmd package install-existing com.skms.android.agent
cmd package install-existing com.sec.factorypm
cmd package install-existing com.sec.android.wallpapercropper2pm 
cmd package install-existing com.sec.android.app.factorykeystringpm 
cmd package install-existing com.sec.android.app.wlantestpm 
cmd package install-existing com.sec.svepm 
cmd package install-existing com.sec.android.providers.securitypm 
cmd package install-existing com.samsung.android.securitylogagentpm 
cmd package install-existing com.samsung.SMTpm 
cmd package install-existing com.samsung.android.aircommandmanagerpm 
cmd package install-existing com.samsung.android.camerasdkservicepm 
cmd package install-existing com.samsung.android.smartfittingpm 
cmd package install-existing com.sec.android.app.SecSetupWizardpm 
cmd package install-existing com.sec.android.app.hwmoduletestpm 
cmd package install-existing com.sec.bcservicepm 
cmd package install-existing com.sec.modem.settingspm 
cmd package install-existing com.sec.android.preloadinstallerpm 
cmd package install-existing com.sec.android.uibcvirtualsoftkeypm 
cmd package install-existing com.sec.imsservicepm 
cmd package install-existing com.samsung.android.da.daagentpm 
cmd package install-existing com.samsung.advp.imssettingspm 
cmd package install-existing com.sec.imsloggerpm 
cmd package install-existing com.sec.android.diagmonagentpm 
cmd package install-existing com.samsung.android.dqagentpm 
cmd package install-existing com.samsung.android.stickercenterpm 
cmd package install-existing com.samsung.android.fmmpm 
cmd package install-existing com.sec.app.RilErrorNotifierpm 
cmd package install-existing com.samsung.android.svcagentpm 
cmd package install-existing com.samsung.android.shortcutbackupservicepm 
cmd package install-existing com.samsung.memorysaverpm 
cmd package install-existing com.android.wallpaperbackuppm 
cmd package install-existing com.samsung.android.app.omcagentpm 
cmd package install-existing com.sec.android.app.personalizationpm 
cmd package install-existing com.samsung.sait.sohservicepm 
cmd package install-existing com.samsung.aasaservicepm 
cmd package install-existing com.samsung.logwriterpm 
cmd package install-existing com.samsung.android.bio.face.servicepm 
cmd package install-existing com.android.mms.servicepm 
cmd package install-existing com.sec.imspm 
cmd package install-existing com.sec.android.CarrierCodeChangerpm 
cmd package install-existing com.sec.android.RilServiceModeApppm 
cmd package install-existing com.samsung.cranepm 
cmd package install-existing com.sec.phonepm 
cmd package install-existing com.sec.android.app.safetyassurancepm 
cmd package install-existing com.samsung.cmhpm 
cmd package install-existing com.samsung.mlppm 
cmd package install-existing com.samsung.storyservicepm 
cmd package install-existing com.samsung.ipservicepm 
cmd package install-existing com.samsung.android.allshare.service.filesharepm 
cmd package install-existing com.samsung.android.beaconmanagerpm 
cmd package install-existing com.samsung.android.allshare.service.mediasharepm 
cmd package install-existing com.samsung.android.scloudpm 
cmd package install-existing com.samsung.android.rubin.apppm 
cmd package install-existing com.samsung.android.sm.devicesecuritypm 
cmd package install-existing com.sec.location.nsflp2pm 
cmd package install-existing com.samsung.android.samsungpositioningpm 
cmd package install-existing com.samsung.android.ipsgeofencepm 
cmd package install-existing com.samsung.android.networkdiagnosticpm 
cmd package install-existing com.sec.android.easyonehandpm 
cmd package install-existing com.samsung.android.aremojipm 
cmd package install-existing com.android.calllogbackuppm 
cmd package install-existing com.sec.android.mimage.avatarstickerspm 
cmd package install-existing com.google.android.configupdaterpm 
cmd package install-existing com.samsung.android.app.siofviewerpm 
cmd package install-existing com.samsung.android.app.dofviewerpm 
cmd package install-existing com.samsung.android.easysetuppm 
cmd package install-existing com.samsung.android.emojiupdaterpm 
cmd package install-existing com.facebook.servicespm 
cmd package install-existing com.samsung.android.app.galaxyfinderpm 
cmd package install-existing com.sec.android.widgetapp.samsungappspm 
cmd package install-existing com.samsung.android.game.gametoolspm 
cmd package install-existing com.google.android.backuptransportpm 
cmd package install-existing com.samsung.android.game.gamehomepm 
cmd package install-existing com.google.android.feedbackpm 
cmd package install-existing com.sec.android.app.samsungappspm 
cmd package install-existing com.google.android.partnersetuppm 
cmd package install-existing com.sec.android.app.fmpm 
cmd package install-existing com.samsung.klmsagentpm 
cmd package install-existing com.samsung.android.keyguardwallpaperupdatorpm 
cmd package install-existing com.samsung.android.mateagentpm 
cmd package install-existing com.sec.vsim.ericssonnsds.webapppm 
cmd package install-existing com.wsomacppm 
cmd package install-existing com.microsoft.skydrivepm 
cmd package install-existing com.sec.spp.pushpm 
cmd package install-existing com.osp.app.signinpm 
cmd package install-existing com.sec.android.app.billingpm 
cmd package install-existing com.sec.android.app.magnifierpm 
cmd package install-existing com.samsung.android.mobileservicepm 
cmd package install-existing com.samsung.android.app.socialpm 
cmd package install-existing com.android.sharedstoragebackuppm 
cmd package install-existing com.google.android.setupwizardpm 
cmd package install-existing com.samsung.android.smartcallproviderpm 
cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preloadpm 
cmd package install-existing com.samsung.android.app.camera.sticker.facearexpression.preloadpm 
cmd package install-existing com.samsung.android.app.camera.sticker.facearframe.preloadpm 
cmd package install-existing com.samsung.android.themestorepm 
cmd package install-existing com.google.android.ext.sharedpm 
cmd package install-existing com.sec.factory.cameralyzerpm 
cmd package install-existing com.sec.android.app.ve.vebgmpm 
cmd package install-existing com.samsung.android.game.gospm 
cmd package install-existing com.monotype.android.font.foundationpm 
cmd package install-existing com.sec.android.splitsoundpm 
cmd package install-existing com.google.android.apps.mapspm 
cmd package install-existing com.google.android.printservice.recommendationpm 
cmd package install-existing com.google.android.syncadapters.contactspm 
cmd package install-existing com.sec.android.widgetapp.webmanualpm 
cmd package install-existing com.google.android.marvin.talkbackpm 
cmd package install-existing com.android.bipspm 
cmd package install-existing com.sec.android.app.chromecustomizationspm 
cmd package install-existing com.monotype.android.font.samsungonepm 
cmd package install-existing com.enhance.gameservicepm 
cmd package install-existing com.samsung.android.app.watchmanagerstubpm 
cmd package install-existing com.samsung.safetyinformationpm 
cmd package install-existing android.autoinstalls.config.samsungpm 
cmd package install-existing com.samsung.android.locationpm 
cmd package install-existing com.sec.unifiedwfcpm 
cmd package install-existing com.samsung.android.sm.policypm 
cmd package install-existing com.android.pacprocessorpm 
cmd package install-existing com.netflix.partner.activationpm 
cmd package install-existing com.hiya.starpm 
cmd package install-existing com.sec.android.app.DataCreatepm 
cmd package install-existing com.samsung.android.smartmirroringpm 
cmd package install-existing com.sec.android.daemonapppm 
cmd package install-existing com.sec.enterprise.knox.cloudmdm.smdmspm 
cmd package install-existing com.samsung.android.lwepm 
cmd package install-existing com.netflix.mediaclientpm 
cmd package install-existing com.sec.android.easyMover.Agentpm 
cmd package install-existing com.aura.oobe.samsungpm 
cmd package install-existing com.opera.max.preinstallpm 
cmd package install-existing com.samsung.android.mfipm 
cmd package install-existing com.mobigraph.xpresso.sliceapppm 
cmd package install-existing com.mygalaxypm 
cmd package install-existing com.samsung.android.game.gospm 
cmd package install-existing com.samsungvietnam.quatanggalaxypm 
cmd package install-existing com.samsung.android.app.watchmanagerpm 
cmd package install-existing com.samsung.android.email.providerpm 
cmd package install-existing com.sec.android.app.voicenotepm 
cmd package install-existing com.google.android.musicpm 
cmd package install-existing com.google.android.videospm 
cmd package install-existing com.linkedin.androidpm 
cmd package install-existing com.google.android.apps.tachyonpm 
cmd package install-existing com.samsung.android.app.panel.naver.vpm 
cmd package install-existing com.sec.android.app.shealthpm 
cmd package install-existing com.samsung.android.vocpm 
cmd package install-existing com.samsung.android.app.notespm 
cmd package install-existing com.samsung.android.spaypm 
cmd package install-existing com.sec.android.easymoverpm 
cmd package install-existing com.rsupport.rs.activity.rsupport.aas2pm 
cmd package install-existing com.sec.android.service.healthpm 
cmd package install-existing com.android.printspoolerpm 
cmd package install-existing com.sec.android.mimage.gear360editorpm 
cmd package install-existing com.samsung.android.oneconnectpm 
cmd package install-existing com.samsung.android.bixby.agentpm 
cmd package install-existing com.microsoft.office.excelpm 
cmd package install-existing com.microsoft.office.powerpointpm 
cmd package install-existing com.android.traceurpm 
cmd package install-existing com.google.android.apps.docs.editors.sheetspm 
cmd package install-existing com.google.mainline.adservicespm 
cmd package install-existing com.google.android.adservices.apipm 
cmd package install-existing com.android.bookmarkproviderpm 
cmd package install-existing com.android.dreams.basicpm 
cmd package install-existing com.android.dreams.phototablepm 
cmd package install-existing com.android.eggpm 
cmd package install-existing com.android.hotwordenrollment.okgooglepm 
cmd package install-existing com.android.hotwordenrollment.xgooglepm 
cmd package install-existing com.android.providers.partnerbookmarkspm 
cmd package install-existing com.sec.android.app.samsungappspm 
cmd package install-existing com.samsung.android.dynamiclockpm 
cmd package install-existing com.samsung.android.tvpluspm 
cmd package install-existing com.samsung.android.app.watchmanagerstubpm 
cmd package install-existing com.samsung.android.app.watchmanagerpm 
cmd package install-existing com.samsung.android.waterpluginpm 
cmd package install-existing com.samsung.android.accessibility.talkbackpm 
cmd package install-existing com.samsung.android.app.settings.bixbypm 
cmd package install-existing com.samsung.android.bixby.wakeuppm 
cmd package install-existing com.samsung.android.bixby.agentpm 
cmd package install-existing com.samsung.android.bixbyvision.frameworkpm 
cmd package install-existing com.sec.android.app.shealthpm 
cmd package install-existing com.samsung.android.arzonepm 
cmd package install-existing com.google.android.apps.docspm 
cmd package install-existing com.google.android.apps.tachyonpm 
cmd package install-existing com.google.android.feedbackpm 
cmd package install-existing com.google.android.googlequicksearchboxpm 
cmd package install-existing com.google.android.marvin.talkbackpm 
cmd package install-existing com.google.android.printservice.recommendationpm 
cmd package install-existing com.google.android.syncadapters.calendarpm 
cmd package install-existing com.google.android.ttspm 
cmd package install-existing com.google.android.apps.youtube.musicpm 
cmd package install-existing com.google.ar.corepm 
cmd package install-existing com.sec.android.mimage.avatarstickerspm 
cmd package install-existing com.samsung.android.aremojieditorpm 
cmd package install-existing com.android.bipspm 
cmd package install-existing com.samsung.android.game.gametoolspm 
cmd package install-existing com.samsung.android.game.gospm 
cmd package install-existing com.samsung.android.kidsinstallerpm 
cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preloadpm 
cmd package install-existing com.sec.android.app.sbrowserpm 
cmd package install-existing com.sec.android.easyMover.Agentpm 
cmd package install-existing com.samsung.android.calendarpm 
cmd package install-existing com.sec.android.dexsystemuipm 
cmd package install-existing com.sec.android.app.desktoplauncherpm 
cmd package install-existing com.synchronoss.dcs.att.r2gpm 
cmd package install-existing com.wavemarket.waplauncherpm 
cmd package install-existing com.pandora.androidpm 
cmd package install-existing com.sec.penuppm 
cmd package install-existing com.wb.goog.got.conquestpm 
cmd package install-existing com.foxnextgames.m3pm 
cmd package install-existing com.microsoft.skydrivepm 
cmd package install-existing com.claromusicapm 
cmd package install-existing com.clarovideopm 
cmd package install-existing com.clarocloudpm 
cmd package install-existing com.claroshoppm 
cmd package install-existing com.claropaypm 
cmd package install-existing com.claro.tvpm 
cmd package install-existing com.claro.empresaspm 
cmd package install-existing com.claro.assistantpm 
cmd package install-existing com.claro.photoeditorpm 
cmd package install-existing com.claro.storepm 
echo " Thanks for Using debloat"
sleep 2
echo ""
echo "I will update new packages to optimize the experience."
echo " Goodbye"
sleep 2