echo " Restore Package"
echo ""
echo " Telegram : @Lusaraemd"
sleep 2 
cmd package install-existing  com.google.android.projection.gearhead
cmd package install-existing  com.google.android.apps.restore
cmd package install-existing   com.samsung.android.aware.service
cmd package install-existing  com.android.wallpaper.livepicker
cmd package install-existing  com.samsung.android.mapsagent
cmd package install-existing com.google.android.syncadap
cmd package install-existing  com.google.android.tts
cmd package install-existing  com.samsung.android.dynamic
cmd package install-existing  com.samsung.android.calenda
cmd package install-existing com.skms.android.agent
cmd package install-existing com.sec.factory
cmd package install-existing com.sec.android.wallpapercropper2 
cmd package install-existing com.sec.android.app.factorykeystring 
cmd package install-existing com.sec.android.app.wlantest 
cmd package install-existing com.sec.sve 
cmd package install-existing com.sec.android.providers.security 
cmd package install-existing com.samsung.android.securitylogagent 
cmd package install-existing com.samsung.SMT 
cmd package install-existing com.samsung.android.aircommandmanager 
cmd package install-existing com.samsung.android.camerasdkservice 
cmd package install-existing com.samsung.android.smartfitting 
cmd package install-existing com.sec.android.app.SecSetupWizard 
cmd package install-existing com.sec.android.app.hwmoduletest 
cmd package install-existing com.sec.bcservice 
cmd package install-existing com.sec.modem.settings 
cmd package install-existing com.sec.android.preloadinstaller 
cmd package install-existing com.sec.android.uibcvirtualsoftkey 
cmd package install-existing com.sec.imsservice 
cmd package install-existing com.samsung.android.da.daagent 
cmd package install-existing com.samsung.advp.imssettings 
cmd package install-existing com.sec.imslogger 
cmd package install-existing com.sec.android.diagmonagent 
cmd package install-existing com.samsung.android.dqagent 
cmd package install-existing com.samsung.android.stickercenter 
cmd package install-existing com.samsung.android.fmm 
cmd package install-existing com.sec.app.RilErrorNotifier 
cmd package install-existing com.samsung.android.svcagent 
cmd package install-existing com.samsung.android.shortcutbackupservice 
cmd package install-existing com.samsung.memorysaver 
cmd package install-existing com.android.wallpaperbackup 
cmd package install-existing com.samsung.android.app.omcagent 
cmd package install-existing com.sec.android.app.personalization 
cmd package install-existing com.samsung.sait.sohservice 
cmd package install-existing com.samsung.aasaservice 
cmd package install-existing com.samsung.logwriter 
cmd package install-existing com.samsung.android.bio.face.service 
cmd package install-existing com.android.mms.service 
cmd package install-existing com.sec.ims 
cmd package install-existing com.sec.android.CarrierCodeChanger 
cmd package install-existing com.sec.android.RilServiceModeApp 
cmd package install-existing com.samsung.crane 
cmd package install-existing com.sec.phone 
cmd package install-existing com.sec.android.app.safetyassurance 
cmd package install-existing com.samsung.cmh 
cmd package install-existing com.samsung.mlp 
cmd package install-existing com.samsung.storyservice 
cmd package install-existing com.samsung.ipservice 
cmd package install-existing com.samsung.android.allshare.service.fileshare 
cmd package install-existing com.samsung.android.beaconmanager
cmd package install-existing com.samsung.android.allshare.service.mediashare 
cmd package install-existing com.samsung.android.scloud 
cmd package install-existing com.samsung.android.rubin.app 
cmd package install-existing com.samsung.android.sm.devicesecurity 
cmd package install-existing com.sec.location.nsflp2 
cmd package install-existing com.samsung.android.samsungpositioning 
cmd package install-existing com.samsung.android.ipsgeofence 
cmd package install-existing com.samsung.android.networkdiagnostic 
cmd package install-existing com.sec.android.easyonehand 
cmd package install-existing com.samsung.android.aremoji 
cmd package install-existing com.android.calllogbackup 
cmd package install-existing com.sec.android.mimage.avatarstickers 
cmd package install-existing com.google.android.configupdater 
cmd package install-existing com.samsung.android.app.siofviewer 
cmd package install-existing com.samsung.android.app.dofviewer 
cmd package install-existing com.samsung.android.easysetup 
cmd package install-existing com.samsung.android.emojiupdater 
cmd package install-existing com.facebook.services 
cmd package install-existing com.samsung.android.app.galaxyfinder 
cmd package install-existing com.sec.android.widgetapp.samsungapps 
cmd package install-existing com.samsung.android.game.gametools 
cmd package install-existing com.google.android.backuptransport 
cmd package install-existing com.samsung.android.game.gamehome 
cmd package install-existing com.google.android.feedback 
cmd package install-existing com.sec.android.app.samsungapps 
cmd package install-existing com.google.android.partnersetup 
cmd package install-existing com.sec.android.app.fm 
cmd package install-existing com.samsung.klmsagent 
cmd package install-existing com.samsung.android.keyguardwallpaperupdator 
cmd package install-existing com.samsung.android.mateagent 
cmd package install-existing com.sec.vsim.ericssonnsds.webapp 
cmd package install-existing com.wsomacp 
cmd package install-existing com.microsoft.skydrive 
cmd package install-existing com.sec.spp.push 
cmd package install-existing com.osp.app.signin 
cmd package install-existing com.sec.android.app.billing 
cmd package install-existing com.sec.android.app.magnifier 
cmd package install-existing com.samsung.android.mobileservice 
cmd package install-existing com.samsung.android.app.social 
cmd package install-existing com.android.sharedstoragebackup 
cmd package install-existing com.google.android.setupwizard 
cmd package install-existing com.samsung.android.smartcallprovider 
cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preload 
cmd package install-existing com.samsung.android.app.camera.sticker.facearexpression.preload 
cmd package install-existing com.samsung.android.app.camera.sticker.facearframe.preload 
cmd package install-existing com.samsung.android.themestore 
cmd package install-existing com.google.android.ext.shared 
cmd package install-existing com.sec.factory.cameralyzer 
cmd package install-existing com.sec.android.app.ve.vebgm 
cmd package install-existing com.samsung.android.game.gos 
cmd package install-existing com.monotype.android.font.foundation 
cmd package install-existing com.sec.android.splitsound 
cmd package install-existing com.google.android.apps.maps 
cmd package install-existing com.google.android.printservice.recommendation 
cmd package install-existing com.google.android.syncadapters.contacts 
cmd package install-existing com.sec.android.widgetapp.webmanual 
cmd package install-existing com.google.android.marvin.talkback 
cmd package install-existing com.android.bips 
cmd package install-existing com.sec.android.app.chromecustomizations 
cmd package install-existing com.monotype.android.font.samsungone 
cmd package install-existing com.enhance.gameservice 
cmd package install-existing com.samsung.android.app.watchmanagerstub 
cmd package install-existing com.samsung.safetyinformation 
cmd package install-existing android.autoinstalls.config.samsung 
cmd package install-existing com.samsung.android.location 
cmd package install-existing com.sec.unifiedwfc 
cmd package install-existing com.samsung.android.sm.policy 
cmd package install-existing com.android.pacprocessor 
cmd package install-existing com.netflix.partner.activation 
cmd package install-existing com.hiya.star 
cmd package install-existing com.sec.android.app.DataCreate 
cmd package install-existing com.samsung.android.smartmirroring 
cmd package install-existing com.sec.android.daemonapp 
cmd package install-existing com.sec.enterprise.knox.cloudmdm.smdms 
cmd package install-existing com.samsung.android.lwe 
cmd package install-existing com.netflix.mediaclient 
cmd package install-existing com.sec.android.easyMover.Agent 
cmd package install-existing com.aura.oobe.samsung 
cmd package install-existing com.opera.max.preinstall 
cmd package install-existing com.samsung.android.mfi 
cmd package install-existing com.mobigraph.xpresso.sliceapp 
cmd package install-existing com.mygalaxy 
cmd package install-existing com.samsung.android.game.gos 
cmd package install-existing com.samsungvietnam.quatanggalaxy 
cmd package install-existing com.samsung.android.app.watchmanager 
cmd package install-existing com.samsung.android.email.provider 
cmd package install-existing com.sec.android.app.voicenote 
cmd package install-existing com.google.android.music 
cmd package install-existing com.google.android.videos 
cmd package install-existing com.linkedin.android 
cmd package install-existing com.google.android.apps.tachyon 
cmd package install-existing com.samsung.android.app.panel.naver.v 
cmd package install-existing com.sec.android.app.shealth 
cmd package install-existing com.samsung.android.voc 
cmd package install-existing com.samsung.android.app.notes 
cmd package install-existing com.samsung.android.spay 
cmd package install-existing com.sec.android.easymover 
cmd package install-existing com.rsupport.rs.activity.rsupport.aas2 
cmd package install-existing com.sec.android.service.health 
cmd package install-existing com.android.printspooler 
cmd package install-existing com.sec.android.mimage.gear360editor 
cmd package install-existing com.samsung.android.oneconnect 
cmd package install-existing com.samsung.android.bixby.agent 
cmd package install-existing com.microsoft.office.excel 
cmd package install-existing com.microsoft.office.powerpoint 
cmd package install-existing com.android.traceur 
cmd package install-existing com.google.android.apps.docs.editors.sheets 
cmd package install-existing com.google.mainline.adservices 
cmd package install-existing com.google.android.adservices.api 
cmd package install-existing com.android.bookmarkprovider 
cmd package install-existing com.android.dreams.basic 
cmd package install-existing com.android.dreams.phototable 
cmd package install-existing com.android.egg 
cmd package install-existing com.android.hotwordenrollment.okgoogle 
cmd package install-existing com.android.hotwordenrollment.xgoogle 
cmd package install-existing com.android.providers.partnerbookmarks 
cmd package install-existing com.sec.android.app.samsungapps 
cmd package install-existing com.samsung.android.dynamiclock 
cmd package install-existing com.samsung.android.tvplus 
cmd package install-existing com.samsung.android.app.watchmanagerstub 
cmd package install-existing com.samsung.android.app.watchmanager 
cmd package install-existing com.samsung.android.waterplugin 
cmd package install-existing com.samsung.android.accessibility.talkback 
cmd package install-existing com.samsung.android.app.settings.bixby 
cmd package install-existing com.samsung.android.bixby.wakeup 
cmd package install-existing com.samsung.android.bixby.agent 
cmd package install-existing com.samsung.android.bixbyvision.framework 
cmd package install-existing com.sec.android.app.shealth 
cmd package install-existing com.samsung.android.arzone 
cmd package install-existing com.google.android.apps.docs 
cmd package install-existing com.google.android.apps.tachyon 
cmd package install-existing com.google.android.feedback 
cmd package install-existing com.google.android.googlequicksearchbox 
cmd package install-existing com.google.android.marvin.talkback 
cmd package install-existing com.google.android.printservice.recommendation 
cmd package install-existing com.google.android.syncadapters.calendar 
cmd package install-existing com.google.android.tts 
cmd package install-existing com.google.android.apps.youtube.music 
cmd package install-existing com.google.ar.core 
cmd package install-existing com.sec.android.mimage.avatarstickers 
cmd package install-existing com.samsung.android.aremojieditor 
cmd package install-existing com.android.bips 
cmd package install-existing com.samsung.android.game.gametools 
cmd package install-existing com.samsung.android.game.gos 
cmd package install-existing com.samsung.android.kidsinstaller 
cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preload 
cmd package install-existing com.sec.android.app.sbrowser 
cmd package install-existing com.sec.android.easyMover.Agent 
cmd package install-existing com.samsung.android.calendar 
cmd package install-existing com.sec.android.dexsystemui 
cmd package install-existing com.sec.android.app.desktoplauncher 
cmd package install-existing com.synchronoss.dcs.att.r2g 
cmd package install-existing com.wavemarket.waplauncher 
cmd package install-existing com.pandora.android 
cmd package install-existing com.sec.penup 
cmd package install-existing com.wb.goog.got.conquest 
cmd package install-existing com.foxnextgames.m3 
cmd package install-existing com.microsoft.skydrive 
cmd package install-existing com.claromusica 
cmd package install-existing com.clarovideo 
cmd package install-existing com.clarocloud 
cmd package install-existing com.claroshop 
cmd package install-existing com.claropay 
cmd package install-existing com.claro.tv 
cmd package install-existing com.claro.empresas 
cmd package install-existing com.claro.assistant 
cmd package install-existing com.claro.photoeditor 
cmd package install-existing com.claro.store 
echo " Thanks for Using Restore Package"
sleep 2
echo ""
echo "I will update new packages to optimize the experience."
echo " Goodbye"
sleep 2
